### ISSUE TITLE
Update axis naming once new axes are accepted into Google Fonts Axis Registry

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/shantell-sans#107]
Aside from visual improvements (drawing, spacing, kerning), the following steps are needed to make these fonts ready to launch.

Next
- [x] check if vertical metrics should really be included in the font (answer: almost certainly not; they are for vertical typesetting)
- [x] fix winAscent & winDescent (set to avoid clipping; useTypeMetrics added)
  - [x] test the result in mac apps
- [x] Run FontBakery on VF and sampling of statics, then add to this list as needed
- [x] narrow down features to single source of truth, then update how calt is added in build-prep
- [x] the static build interpolates UFOs _twice_ – once for TTFs, and again for OTFs. Simplify this.
- [x] set underline and strikethrough values
- [x] update `GDEF` in features during build-prep
- [x] maybe change pseudo-random code from calt to rlig? ([discussion](https://typedrawers.com/discussion/2979/the-differnce-between-rlig-and-liga)). This would more strictly ensure that randomness is "on" for users, and would leave the yukrcyr_yukrcyr ligature alone in calt.
  - [x] update static subsetter to remove rlig, not calt, in normal instances
  - [x] test rlig with tracking… it should work but would be good to know (result: yes, it works even when tracking is turned up, as tested in Safari, Chrome, and InDesign)
- [x] test 1.005 build with fewer instances (https://github.com/googlefonts/axisregistry/issues/38#issuecomment-1234833552)
- [x] make "prepped for google fonts" release folder, similar to Recursive
- [x] add `zero` feature for slashed zero, because it’s nice

Based on fontbakery run with latest version of fontbakery
- [x] prevent build from generating `.alt3` glyphs if they are not in the `uppercase` or `lowercase` variables (making them unreachable in the simpler part of the rlig feature)
- [x] add the "dotted circle character (U+25CC)"
- [x] ~remove overlaystrokeshortcmb from GDEF marks category~ Not important.
- [x] ~add meta table (requires research)~ FontMake doesn't seem to do this yet, as far as I can tell. https://github.com/googlefonts/fontmake/issues/934. I probably won’t add it unless it becomes important.
- [x] ~add ligature carets (anchors starting with `caret_` for fontmake)~ Not important.
- [x] debug STAT table adding

Also
- [x] decide whether/how to define axes on web specimen
- [x] Feedback from Yanone (#114)

Finally...
- [x] add OFL license to main
- [x] make repo public
- [x] get axis definition PRs merged
- [x] change axis naming, if required
- [ ] (once axes are merged) PR font to google/fonts; get Yanone’s help

**Comment by arrowtype** [comment]
- [ ] Adjust contours to avoid this overlap-removal issue:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/45946693/189207166-3fc7d968-e276-4c66-b30a-d53ddd657b88.png">

**Comment by arrowtype** [comment]
Questions asked and answered on a Google Fonts weekly meeting:
- Is it important to add a meta table? 
- Is it important to add ligature carets? 
- Is it important to remove  overlaystrokeshortcmb from GDEF marks category?

Answers: if they are only `warn` level messages in FontBakery, these are safe to ignore for now.
