### ISSUE TITLE
Tasks to complete for release v1.0

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/shantell-sans#19]
**Font data**
- [x] reduce filesize of "Normal" static fonts https://github.com/arrowtype/shantell-sans/issues/16
- [x] set metric values (e.g. adjust hhea & typo metrics) – set with `scripts--robofont/set-font-info-sel_fonts.py` – commented below
- [ ] Run FontBakery universal/googlefonts checks and fix flagged issues – https://github.com/arrowtype/shantell-sans/issues/23

**Final character additions - https://github.com/arrowtype/shantell-sans/issues/5 & https://github.com/arrowtype/shantell-sans/issues/23**
- [x] `one.prop` – actually, add proportional figures (pnum) for 0-9, then kern
- [x] adjust `dollar` width
- [x] `currency`
- [x] `brokenbar`
- [x] `multiply`
- [x] `minus` (probably just add the unicode to `hyphen`)
- [x] `divisionslash`
- [ ] softhyphen (?)
- [x] .notdef

**Determine specific build prep**
- [x] alts decided in https://github.com/arrowtype/shantell-sans/issues/21
- [x] contextual alternates (randomization) finalized with https://github.com/arrowtype/shantell-sans/blob/0debaf42ccd404ad336f9aa28655eebac9c31061/scripts--build/prep-build.py

**Irregular sources**
- [x] do a pass of spacing fixes to irregular sources
- [x] then re-build accented characters
- [x] make numbers irregular in light irregular source

**Kerning**
- [x] kern punc against letters: `« “ ‘ [ ( {` to `A–Z a–z`, with closing
- [x] kern .case punc against uppercase
- [x] import updated groups to irregular sources
- [ ] additional proofs for uc & lc kern fixes
- [x] kern TM against lowercase

**Other fixes, all weights**
- [x] fix incompatible `zdotaccent` & `Zdotaccent`
- [x] steeper `Ł` crossbar
- [x] put partial center slash in `ø`
- [x] check uppercase accents vs `hhea.ascent`
- [x] ~less-wide `o`(?)~ no, the `o`s in sketches are very round or even wide ellipses
- [x] narrower `I`
- [x] add proportional `1` then add prop OT feature; make `$` tabular width https://github.com/arrowtype/shantell-sans/issues/5
- [x] add tabular `comma` and `period` for tnum feature
- [x] add `ordn` feature for Portugese & Spanish
- [x] Is the Bouncy axis too extreme? Should `Semi-Bouncy` be less intense? Yes, I think it should be 25 rather than 50

**Other fixes in light**
- [x] thinner quotes & comma
- [x] sharper `Z`?
- [x] softer `M`?

**Other fixes in bold**
- [x] thin out `e` `ae` `oe`
- [x] thin out `M`

**Build fixes**
- [x] determine why punctuation not yet kerning properly with alts against alts. Fixed with https://github.com/arrowtype/shantell-sans/commit/7755897d7214d9da15ce325cd52cf5c87324c141

**Other release tasks**
- [x] remove `references/scans-2020_06_18` with BFG
- [x] updating contributing doc
